### ISSUE TITLE
Make project creation dependent on IAM role

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-bootstrap#14]
Currently, errors will occur if the admin running bootstrap doesn't have the project creator role.

We should update the dependency graph so that the proper IAM roles are granted before project creation is attempted.

**Comment by rjerrems** [comment]
G'day @morgante - this is actually detailed in the readme under the permissions section. Currently the module assumes the runner of this module is in the `group_org_admins` group. We could either make that documentation clearer or look at an alternative?

Cheers,
Rohan

**Comment by morgante** [comment]
Correct - my goal is actually to simplify the configuration so the *only* role needed is `roles/resourcemanager.organizationAdmin`. Since we're already provisioning the additional roles within this module, there shouldn't be any need to have them added out-of-band. Instead, we should make any resources which require them to have a `depends_on` the IAM resource.

**Comment by rjerrems** [comment]
Yeah cool sounds good. I think we can achieve the dependency using something like a data lookup for the organization which is then subsequently used in the project factory module.

**Comment by rjerrems** [comment]
I have created a pull request @morgante - in the end I opted for provided code in examples which makes sure projectCreator permissions are applied rather than adding the same code to both the main module and the cloudbuild submodule. The dependencies are a little complicated because of the usage of `google_organization_iam_binding` for project creator permissions for both the terraform service account and the org admins group in the main module.

Let me know if you think there is a better way.
